; Speed-Net STM32WB5MM-DK Firmware
; PlatformIO configuration

[env:stm32wb5mm_dk]
platform = ststm32
board = stm32wb5mm_dk
framework = arduino

; Libraries
lib_deps =
    olikraus/U8g2@^2.35
    bblanchon/ArduinoJson@^7

; Serial monitor
monitor_speed = 115200

; Build flags
build_flags =
    -D SSD1315_OLED
    -D SERIAL_BAUD=115200
